ignored = [
    "github.com/miekg/dns",
    "golang.org/x/net/context",
    "golang.org/x/net/context/ctxhttp",
    "golang.org/x/net/http2",
    "golang.org/x/net/http2/hpack",
    "golang.org/x/net/idna",
    "golang.org/x/net/internal/timeseries",
    "golang.org/x/net/lex/httplex",
    "golang.org/x/net/trace",
]

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
    name = "github.com/openzipkin/zipkin-go-opentracing"
    version = "v0.2.3"

[[constraint]]
  name = "github.com/mholt/caddy"
  version = "0.10.9"
